import AppKit
import CompassCore

/// クリップボードの履歴を持つ。
///
/// **独立したモジュールにしてある**（requirements.md 2章）。全コピー内容をディスクへ
/// 永続化するという責務の性質がランチャーと異なるため、将来の除外設定や、丸ごと
/// 切り離す判断に備える。`config.toml` の `clipboard.enabled = false` で監視ごと止まる。
@MainActor
public final class ClipboardHistory {

    /// **履歴に残さない pasteboard type。**
    ///
    /// パスワードマネージャなどが「これは保存するな」と示すために付ける印。
    /// 拾ってしまうとパスワードが平文でディスクに残る。nspasteboard.org の慣例に従う。
    private static let excludedTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
    ]

    public private(set) var items: [String] = []

    private let settings: @MainActor () -> Config.Clipboard
    private let storeURL: URL
    private let log: Log
    private var poller: ManagedSource?
    private var lastChangeCount: Int

    public init(
        settings: @escaping @MainActor () -> Config.Clipboard,
        storeURL: URL = ClipboardHistory.defaultStoreURL,
        log: Log = .shared
    ) {
        self.settings = settings
        self.storeURL = storeURL
        self.log = log
        // 起動時点の内容は履歴に入れない。既にコピー済みのものを「今コピーした」
        // 扱いにすると、再起動のたびに同じ項目が先頭へ来る。
        self.lastChangeCount = NSPasteboard.general.changeCount
        load()
    }

    /// `~/Library/Application Support/compass/clipboard.json`
    public nonisolated static var defaultStoreURL: URL {
        FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent("Library/Application Support/compass", isDirectory: true)
            .appendingPathComponent("clipboard.json")
    }

    public var isRunning: Bool { poller != nil }

    // MARK: - 監視

    /// 監視を始める。`enabled = false` なら何もしない。
    public func start() {
        stop()

        let configuration = settings()
        guard configuration.enabled else {
            log.debug("クリップボード監視は無効")
            return
        }

        // `NSPasteboard` に変更通知は無い。ポーリングしかない（requirements.md 3.4）。
        //
        // **`Timer` は使わない。** `scheduledTimer` は run loop の `.default` モードに
        // だけ載るため、メニューを開いている間やウィンドウをドラッグしている間
        // （`.eventTracking`）は止まる。その隙に 2 回コピーすると 1 回目を取りこぼす。
        // メインキューの dispatch timer はモードに関係なく回る。
        let interval = configuration.pollInterval
        let source = DispatchSource.makeTimerSource(queue: .main)
        source.schedule(
            deadline: .now() + interval,
            repeating: interval,
            // 厳密な間隔は要らない。まとめて起こしてもらって消費電力を抑える。
            leeway: .milliseconds(Int(interval * 250))
        )
        source.setEventHandler { [weak self] in
            MainActor.assumeIsolated { self?.poll() }
        }
        source.resume()
        poller = ManagedSource(source)

        log.debug("クリップボード監視を開始: \(interval) 秒間隔")
    }

    /// 監視を止める。**参照を捨てるだけ**で `ManagedSource` が cancel する。
    public func stop() {
        poller = nil
    }

    private func poll() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        if let types = pasteboard.types,
            types.contains(where: { Self.excludedTypes.contains($0.rawValue) })
        {
            log.debug("履歴に残さない印が付いていたので無視した")
            return
        }

        // テキストのみ。画像とファイルは対象外（requirements.md 3.4）。
        guard let text = pasteboard.string(forType: .string), !text.isEmpty else { return }
        record(text)
    }

    /// 履歴へ入れる。テストから直接呼ぶ。
    func record(_ text: String) {
        // 同じ内容は消して先頭へ移す（requirements.md 3.4）。
        items.removeAll { $0 == text }
        items.insert(text, at: 0)

        let maxItems = settings().maxItems
        if items.count > maxItems {
            items.removeLast(items.count - maxItems)
        }
        save()
    }

    public func clear() {
        items = []
        save()
    }

    // MARK: - 候補

    /// 一覧に出す候補。新しいものが上。
    public func candidates() -> [Candidate] {
        items.enumerated().map { index, text in
            Candidate(
                id: "clipboard:\(index)",
                title: TextSummary.line(of: text),
                icon: .symbol("doc.on.clipboard"),
                action: .paste(text)
            )
        }
    }

    // MARK: - 永続化

    /// 書き込みを直列に流すキュー。
    ///
    /// **メインスレッドで書かない。** コピーのたびに履歴を丸ごと JSON へ直して
    /// 書き直すので、大きなテキストをコピーすると入力がその分だけ止まる。
    /// 直列にしておけば、続けてコピーしても書き込み順が入れ替わらない。
    private nonisolated static let writeQueue = DispatchQueue(
        label: "org.compass.clipboard.write", qos: .utility)

    private func save() {
        let snapshot = items
        let url = storeURL
        let log = self.log
        Self.writeQueue.async {
            Self.write(snapshot, to: url, log: log)
        }
    }

    /// 書き込みが終わるまで待つ。**テストから読み返す前に使う。**
    func waitForWrites() {
        Self.writeQueue.sync {}
    }

    private nonisolated static func write(_ items: [String], to url: URL, log: Log) {
        let directory = url.deletingLastPathComponent()
        do {
            try FileManager.default.createDirectory(
                at: directory, withIntermediateDirectories: true)
            let data = try JSONEncoder().encode(items)
            try data.write(to: url, options: .atomic)
            // **他のユーザーから読めないようにする。** 履歴は機密を含みうる。
            try FileManager.default.setAttributes(
                [.posixPermissions: 0o600], ofItemAtPath: url.path)
        } catch {
            log.error("クリップボード履歴を保存できなかった: \(error.localizedDescription)")
        }
    }

    private func load() {
        guard let data = try? Data(contentsOf: storeURL) else { return }
        guard let stored = try? JSONDecoder().decode([String].self, from: data) else {
            // 壊れていても起動は止めない。空から始める。
            log.warn("クリップボード履歴を読めなかった。空から始める: \(storeURL.path)")
            return
        }
        items = stored
        log.debug("クリップボード履歴を読み込んだ: \(items.count) 件")
    }
}
